apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: travelr-pgadmin-tls # TLSにつける名前
  namespace: default
spec:
  secretName: travelr-pgadmin-tls # TLSにつける名前
  issuerRef:
    name: letsencrypt-prod # 作成したClusterIssuerの名前
    kind: ClusterIssuer
  commonName: travelr-pgadmin.yuuniworks.com # ドメイン
  dnsNames:
  - travelr-pgadmin.yuuniworks.com # ドメイン
  acme:
    config:
    - http01:
        ingress: my-ingress # 使用しているIngressの名前
      domains:
      - travelr-pgadmin.yuuniworks.com # ドメイン
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: travelr-api-tls # TLSにつける名前
  namespace: default
spec:
  secretName: travelr-api-tls # TLSにつける名前
  issuerRef:
    name: letsencrypt-prod # 作成したClusterIssuerの名前
    kind: ClusterIssuer
  commonName: travelr-api.yuuniworks.com # ドメイン
  dnsNames:
  - travelr-api.yuuniworks.com # ドメイン
  acme:
    config:
    - http01:
        ingress: my-ingress # 使用しているIngressの名前
      domains:
      - travelr-api.yuuniworks.com # ドメイン