apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx # この一文を入れると、Ingressはロードバランサを作成しない。
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: travelr-pgadmin-tls
    hosts:
    - travelr-pgadmin.yuuniworks.com
  - secretName: travelr-api-tls
    hosts:
    - travelr-api.yuuniworks.com
  rules:
  - host: travelr-pgadmin.yuuniworks.com
    http:
      paths:
      - backend:
          serviceName: travelr-pgadmin-svc
          servicePort: 80
  - host: travelr-api.yuuniworks.com
    http:
      paths:
      - backend:
          serviceName: travelr-api-svc
          servicePort: 80
