apiVersion: v1
kind: Service
metadata:
  name: travelr-postgres-svc # この名前でpodから名前解決できる
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: travelr-postgres
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: travelr-postgres-dpl
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: travelr-postgres
    spec: # pod spec
      volumes:
      - name: volume-travelr-postgres
        persistentVolumeClaim:
          claimName: pvc-travelr-postgres
      containers:
      - name: travelr-postgres
        image: mdillon/postgis:10-alpine
        resources:
          requests:
            cpu: 0
            memory: 0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: travelr_postgres_admin_pass
        # postgres initialization fails if GCE disk is mounted
        # to '/var/lib/postgresql/data' which is postgres default data folder.
        # this is because GCE disk contains 'lost+fount' folder in its root.
        # so data folder neeed to be changed its subfolder(in this case, 'pgdata').
        #
        # SEE:
        # https://github.com/docker-library/postgres/issues/263
        # https://hub.docker.com/_/postgres/ (PGDATA section)
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata/"
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: volume-travelr-postgres
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
# postgres用PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-travelr-postgres
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: pv-travelr-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
---
# postgres用PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-travelr-postgres
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce # 1台のポッドにRWでマウント
  # run following command once before use th disk
  # gcloud compute disks create --size=10GB --zone=asia-northeast1-a --type=pd-ssd disk-for-travelr-postgres
  gcePersistentDisk:
    pdName: disk-for-travelr-postgres # 手動で作成したDiskの名前。PV/PVCを削除してもディスクは削除されない。
    fsType: ext4
